name = "ScoringEngineDemo"
uuid = "2e1be78e-94a1-43b6-9407-8099e760a385"
authors = ["jeremie.db <jeremie.bouchard@juliacomputing.com>"]
version = "0.1.0"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
EvoTrees = "f6006082-12f8-11e9-0c9c-0d5d367ab1e5"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JSONTables = "b9914132-a727-11e9-1322-f18e41205b0b"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
ParameterSchedulers = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
ShapML = "8523bd24-6f66-414b-9e1e-b02db3916d64"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"
StipplePlotly = "ec984513-233d-481d-95b0-a3b58b97af2b"
StippleUI = "a3c5d34a-b254-4859-a8fa-b86abb7e84a3"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
CSV = "0.8"
